# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'candlesticks_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Candlesticks_dialog(object):
    def setupUi(self, Candlesticks_dialog):
        Candlesticks_dialog.setObjectName("Candlesticks_dialog")
        Candlesticks_dialog.resize(349, 136)
        self.label = QtWidgets.QLabel(Candlesticks_dialog)
        self.label.setGeometry(QtCore.QRect(30, 50, 101, 21))
        self.label.setObjectName("label")
        self.candlesticks_comboBox = QtWidgets.QComboBox(Candlesticks_dialog)
        self.candlesticks_comboBox.setGeometry(QtCore.QRect(142, 50, 181, 22))
        self.candlesticks_comboBox.setObjectName("candlesticks_comboBox")
        self.Generate_candlestick = QtWidgets.QPushButton(Candlesticks_dialog)
        self.Generate_candlestick.setGeometry(QtCore.QRect(240, 90, 93, 28))
        self.Generate_candlestick.setObjectName("Generate_candlestick")

        self.retranslateUi(Candlesticks_dialog)
        QtCore.QMetaObject.connectSlotsByName(Candlesticks_dialog)

    def retranslateUi(self, Candlesticks_dialog):
        _translate = QtCore.QCoreApplication.translate
        Candlesticks_dialog.setWindowTitle(_translate("Candlesticks_dialog", "Dialog"))
        self.label.setText(_translate("Candlesticks_dialog", "Choose option"))
        self.Generate_candlestick.setText(_translate("Candlesticks_dialog", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Candlesticks_dialog = QtWidgets.QDialog()
    ui = Ui_Candlesticks_dialog()
    ui.setupUi(Candlesticks_dialog)
    Candlesticks_dialog.show()
    sys.exit(app.exec_())
